### ISSUE TITLE
Found some errors while trying to onboard. 

### ISSUE THREAD

**Issue by minitriga** [jeremyschulman/ipf-netbox#11]
Lets have a chat this week and we can look into some of these issues:

- Slugify function is required... Maybe reuse the one from device type import? 
```bash
(venv) agitting@dev:~/python/ipf-netbox$ ipf-netbox task ensure-sites
Ensure Netbox contains the Sites defined in IP Fabric
Fetching from IP Fabric and Netbox ... 
IP Fabric 1 items.
Netbox 1 items.
Site Name    Exists
-----------  --------
Axians Lab   No
CREATE site: Axians Lab: FAIL: {"slug":["Enter a valid \"slug\" consisting of letters, numbers, underscores or hyphens."]}
```

- When IPFabric does not discover a model its None but platform is used as the model. 
This can be seen here:
![image](https://user-images.githubusercontent.com/26367336/98489856-9becfa00-2227-11eb-9b39-a2f4709e97fc.png)
maybe in devices if the model is none we check if there is a platform to device type mapping.

**Comment by jeremyschulman** [comment]
@minitriga - per your DM, is this issues still relevant?  If not, please close.  Thank you.

**Comment by minitriga** [comment]
@jeremyschulman No ill close.
